mission:
  budget: 20000
  spent_budget: 0
  total_cargo_weight: 0
  goal_weight: 2500
  lost_weight: 0
  delivered_weight: 0

  bases:
    a_base:
      x: 0
      y: 0
    b_base:
      x: 100
      y: 50

  pirates_bases:
    - x: 75
      y: 25
    - x: 80
      y: 30
    - x: 70
      y: 20

  map:
    dx: 150
    dy: 100
    center:
      x: 50
      y: 25
